[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/opt/buildhome/.nvm/versions/node/v18.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://refugio-natural.netlify.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview-${REVIEW_ID}--refugio-natural.netlify.app"
